### ISSUE TITLE
Allow to parse JSON objects that have nested JSON strings as value of a property

### ISSUE THREAD

**Issue by dardesantis** [dardesantis/DJSON-Viewer#3]

**Comment by andyil** [comment]
I want this

**Comment by dardesantis** [comment]
initial support added in [v.0.4.1](https://github.com/dardesantis/DJSON-Viewer/releases/tag/v0.4.1) using selection context menu striping slashes

**Comment by dardesantis** [comment]
Added in v0.4.3
