### ISSUE TITLE
Preference "Format JSON as collapsed" should expand at least one tree level

### ISSUE THREAD

**Issue by olconstant** [dardesantis/DJSON-Viewer#6]
I find quite useless to show a totally collapsed JSON.
Also if the JSON is too big, it can be automatically collapsed to avoid lag.

What do you think?

Great job BTW!

**Comment by ddesantis** [comment]
You're totally right... I will change to show 1 level open.

If you have any more suggestions or feature request don't hesitate to open new issues.

Thanks

**Comment by dardesantis** [comment]
Added in v0.4.3
