### ISSUE TITLE
Extend Collapse children logic to Collapse All button

### ISSUE THREAD

**Issue by olconstant** [dardesantis/DJSON-Viewer#7]
Thx @dardesantis, the Format JSON with collapsed children option works perfectly in v0.4.3. The option is very useful now!

Maybe we can extend the same logic to the Collapse All button as well, because it's also useless to show totally collapsed JSON here, what do you think?

The option behaviour will be more consistent. And if an user really wants to show a totally collapsed JSON, he can do it manually very easily.

**Comment by dardesantis** [comment]
changed in v0.4.4.

Thanks
