### ISSUE TITLE
Add a new option preference to collapse children for big JSON only

### ISSUE THREAD

**Issue by olconstant** [dardesantis/DJSON-Viewer#8]
It will be interesting to add a new option preference: Format JSON with collapsed children only for big JSON.

It's not an absolute must have, but will be useful for user working with very big JSON and normal size JSON. When the JSON is big, show collapsed children will avoid Chrome to lag during scrolling. For JSON with normal size, there is no reason to show collapsed children.

I don't know wether it's hard to do, but it can be an interesting new feature.

**Comment by dardesantis** [comment]
Added as option in v0.4.4
